src/detail.hbs, src/index.hbs
=> Using markdown for Description fields

src/detail.hbs
This will allow more varied content in the field and also supports things like emails better.
=> Changing Contact field to a markdown field

gulpfile.js
=> Force slug to be lowercase independent of filename

gulpfile.js, src/partials/header.hbs, src/rss.xml.hbs
=> Adding rss feed at /rss.xml

src/css/main.css
=> Change display to inline-block for tags.

gulpfile.js, src/examples.hbs, src/index.hbs, src/js/index.js, src/js/tags.js, src/partials/about.hbs, src/partials/header.hbs, src/sitemap.hbs
Adds an individual page for each tag, of the form https://registry.opendata.aws/sustainability/. Also adds to sitemap for indexing.
closes #40
=> Adding a page for each tag

src/detail.hbs
Ref https://github.com/awslabs/open-data-registry/issues/201
=> Using markdown for Documentation field

package-lock.json, package.json
=> Updating for lodash vulnerability

README.md, gulpfile.js
=> Adding tag/{tag}/datasets.yaml

gulpfile.js, package.json, src/detail.hbs, src/js/index.js
=> Adding link to see other datasets managed by the same group

gulpfile.js
=> Apply AWS tag to more Usage Examples

src/collabs/stsci.yaml
=> First hack at description of STScI.

src/collabs/noaa.yaml
=> Adding NOAA datasets

gulpfile.js, src/index.hbs, src/partials/about.hbs
=> Call out collabs on main page

src/partials/about.hbs
=> Fixing collab routing

src/index.hbs
Absolute links for details & usage examples so they work on collab & tag pages.
=> fix(links): Absolute links so collab pages work

Dockerfile, README.md, gulpfile.js, src/css/main.css, src/detail.hbs, src/index.hbs
feat(sustainability): Sustainability tags green
feat(tags): Sorted alphabetically
feat(docker): Added for dev
=> Green sustainability

gulpfile.js, src/css/main.css, src/detail.hbs, src/examples.hbs, src/index.hbs, src/partials/detailList.hbs
=> DataAtWork updates

README.md, gulpfile.js, src/config.yaml, src/partials/header.hbs, src/redirect.hbs
=> Can now add redirects via config.yaml

package-lock.json, package.json
=> Adding natives package for build purposes

.travis.yml, _scripts/deploy.sh, buildspec.yml
=> Moving to CodeBuild for CI/CD

gulpfile.js
=> Catch docs.opendata.aws as AWS property

src/config.yaml
=> Redirect deprecated usda naip

src/partials/header.hbs
=> Adding favicon links

gulpfile.js, src/partials/header.hbs
=> fix(quotes): Escape quotes for json

README.md, gulpfile.js, package-lock.json, package.json
=> Adding ndjson of datasets

_scripts/deploy.sh
=> Updating master

README.md, src/collabs/nasa.yaml
=> Deploying latest

gulpfile.js
Closes https://github.com/awslabs/open-data-registry-browser/issues/132
=> Adding go.aws to highlighted links

gulpfile.js, src/collabs/noaa.yaml, tests/test-data-compare/index.html
* List ASDI as a collab
* Update test & NOAA collab
=> List ASDI (#128)

gulpfile.js, src/detail.hbs, tests/test-data-compare/landsat-8.html
=> Add AWS CLI links (#140)

src/collabs/noaa.yaml, tests/test-data-compare/index.html
=> Project -> Program

gulpfile.js, src/detail.hbs, tests/test-data-compare/landsat-8.html
=> BDP: Big Data Program

package.json, src/partials/header.hbs, tests/test-data-compare/change-log.html, tests/test-data-compare/index.html, tests/test-data-compare/landsat-8.html
=> Bootstrap -> 3.4.1

_scripts/copy-data.sh, gulpfile.js
=> Update for multiple data sources (#149)

package-lock.json, package.json
=> Upping object-path version

src/partials/header.hbs, tests/test-data-compare/change-log.html, tests/test-data-compare/index.html, tests/test-data-compare/landsat-8.html
=> Updating jquery version

src/partials/header.hbs, tests/test-data-compare/change-log.html, tests/test-data-compare/index.html, tests/test-data-compare/landsat-8.html
=> Updating jquery version (#155)

src/detail.hbs
=> Add Explore section for resources

package-lock.json, src/detail.hbs
=> Dependency Bump

package-lock.json, package.json
=> Update BrowserSync version

package-lock.json, src/detail.hbs
=> Bump versions

gulpfile.js, tests/test.js
=> Adding YouTube playlist that gets AWS content label

README.md
=> Adding index.ndjson callout

src/asdi/asdi.yaml
=> Update ASDI text

src/partials/about.hbs, tests/test-data-compare/change-log.html, tests/test-data-compare/index.html
=> Making change-log more prominent

gulpfile.js, src/detail.hbs, tests/test-data-compare/landsat-8.html
=> Adding How to Cite section

src/collabs/deafrica.yaml
More DE Africa datasets, relates to https://github.com/awslabs/open-data-registry/pull/1201
=> Add more DE Africa datasets

src/config.yaml
=> Adding fb -> meta redirect

src/collabs/deafrica.yaml
=> Adding DE Africa video

src/config.yaml
=> redirect cmip5 to new url

src/collabs/noaa.yaml
=> update noaa collab

src/js/banner.js, src/partials/header.hbs
=> Changing button code location

tests/test-data-compare/change-log.html, tests/test-data-compare/index.html, tests/test-data-compare/usgs-landsat.html
=> Updating tests

gulpfile.js
=> Limiting tutorials on service pages to only those matching the service

src/examples.hbs, src/partials/detailList.hbs
=> Removing service labels on service page

src/collabs/noaa.yaml, tests/test-data-compare/index.html
=> NOAA BDP to NODD rename

src/collabs/nasa.yaml
=> updated nasa collab

src/collabs/noaa.yaml
=> Update NOAA collab adding new datasets

src/collabs/stsci.yaml
=> Update stsci.yaml with add'l datasets

src/collabs/nasa.yaml
=> update nasa saa collab page 

src/collabs/nasa.yaml
=> nasa collab update

Dockerfile
Aid local testing by bumping to a supported docker image
=> bump base image for Dockerfile
